# Generated by Django 3.0.6 on 2020-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_index=True, max_length=64, verbose_name='time')),
                ('activPower', models.CharField(db_index=True, max_length=64, verbose_name='activ_power')),
                ('reactivPower', models.CharField(db_index=True, max_length=64, verbose_name=' reactiv_power')),
            ],
        ),
    ]
